[package]
name = "the_tracker"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
path = "src/lib.rs"

[workspace]
members = [".", "db_updater", "issues_tracker"]
exclude = ["db_updater_local", "issues_tracker_local"]

[dependencies]
issues_tracker = { version = "0.1.0", path = "issues_tracker" }
db_updater = { version = "0.1.0", path = "db_updater" }
dotenv = "0.15.0"
serde_json = "1.0.97"
tokio_wasi = { version = "1", features = ["rt", "macros", "net", "time"] }
serde = { version = "1", features = ["derive"] }
anyhow = "1.0.75"
flowsnet-platform-sdk = "0.1.3"
log = "0.4.14"
schedule-flows = "0.3.0"
chrono = "0.4.31"
github-flows = "0.7.0"
octocrab_wasi = { version = "0.19.1", features = ["wasi"], default-features = false }
base64 = "0.21.5"
derivative = "2.2.0"
openai-flows = "0.9.1"
web-scraper-flows = "0.1.0"
regex = "1.10.3"
itertools = "0.12.1"
store-flows = "0.3.1"
http_req_wasi = { version = "0.11.1", features = ["wasmedge_rustls"] }
urlencoding = "2.1.3"
sqlx = { version = "0.7.3", features = ["postgres", "runtime-tokio-native-tls", "bigdecimal"] }

# Adding sqlx v0.7.3 to dependencies
# Features:
# + _rt-tokio
# + any
# + bigdecimal
# + json
# + macros
# + migrate
# + postgres
# + runtime-tokio
# + runtime-tokio-native-tls
# + sqlx-macros
# + sqlx-postgres
# + tls-native-tls
# 21 deactivated features

# compile_error!("Only features sync,macros,io-util,rt,time are supported on wasm.");