query ($owner: String!, $repo: String!) {
  repository(owner: $owner, name: $repo) {
    owner {
      login
      ... on User {
        avatarUrl
      }
      ... on Organization {
        avatarUrl
      }
    }
  }
}
{
  "owner": "jaykchen",
  "repo": "a-test"
}