query ($owner: String!, $repo: String!, $issueNumber: Int!) {
  repository(owner: $owner, name: $repo) {
    issue(number: $issueNumber) {
      title
      number
      body
      comments(first: 10) {
        # Adjust the 'first' parameter to fetch more comments
        edges {
          node {
            author {
              login
            }
            body
            createdAt
          }
        }
      }
    }
  }
}
{
  "owner": "warmachine028",
  "repo": "nike",
  "issueNumber": 190
}