query ($owner: String!, $repo: String!, $issueNumber: Int!) {
  repository(owner: $owner, name: $repo) {
    pullRequest(number: $issueNumber) {
      title
      number
      author {
        login
      }
      labels(first: 10) {
        edges {
          node {
            name
          }
        }
      }
      reviews(first: 10) {
        edges {
          node {
            author {
              login
            }
            state
          }
        }
      }
      assignees(first: 10) {
        edges {
          node {
            name
          }
        }
      }
      timelineItems(
        first: 200
        itemTypes: [CLOSED_EVENT, MERGED_EVENT, CROSS_REFERENCED_EVENT]
      ) {
        edges {
          node {
            __typename
            ... on ClosedEvent {
              actor {
                login
              }
              createdAt
            }
            ... on MergedEvent {
              actor {
                login
              }
              createdAt
            }
            ... on IssueComment {
              author {
                login
              }
              body
              createdAt
            }
            ... on CrossReferencedEvent {
              actor {
                login
              }
              source {
                __typename
                ... on Issue {
                  number
                  title
                  url
                }
              }
              createdAt
            }
          }
        }
      }
    }
  }
}

{
  "owner": "ohmyzsh",
  "repo": "ohmyzsh",
  "issueNumber": 8277
}
