[package]
name = "db_updater_mysql"
version = "0.1.0"
edition = "2021"

[workspace]

 
[dependencies]
anyhow = "1.0"
futures = "0.3"
tokio = { version = "1.20.0", features = ["rt", "macros"]}
dotenvy = "0.15.0"
dotenv = "0.15.0"
mysql_async = "0.33.0"
