query($query: String!, $firstIssues: Int!, $firstComments: Int!) {
  search(query: $query, type: ISSUE, first: $firstIssues) {
    issueCount
    edges {
      node {
        ... on Issue {
          title
          number
          body
          author {
            login
            ... on User {
              avatarUrl
            }
          }
          repository {
            name
            owner {
              login
            }
          }
          labels(first: 10) {
            edges {
              node {
                name
              }
            }
          }
          comments(first: $firstComments) {
            edges {
              node {
                author {
                  login
                }
                body
              }
            }
          }
        }
      }
    }
  }
}

{
    "query": "label:hacktoberfest is:issue is:open no:assignee created:>2023-10-01",
    "firstIssues": 100,
    "firstComments": 10
  }
  
  {
    "query": "label:hacktoberfest is:issue is:open no:assignee created:>2023-10-01 sort:interactions-desc",
    "firstIssues": 100,
    "firstComments": 10
  }

#   Author: author:<username>
# Milestone: milestone:<milestone>
# Assignee: assignee:<username>
# Commenter: commenter:<username>
# Created: created:<date>
# Updated: updated:<date>
# Closed: closed:<date>
# Labels: label:<label>
# Projects: project:<project>
# Reactions: reactions:<reaction>
# Review requests: review-requested:<username>
# Review comments: review-commenter:<username>
# You can combine multiple filter conditions using the following operators:

# AND: condition1 condition2
# OR: condition1 OR condition2
# NOT: NOT condition