query ($query: String!, $firstIssues: Int!) {
  search(query: $query, type: ISSUE, first: $firstIssues) {
    issueCount
    edges {
      node {
        ... on PullRequest {
          title
          number
          url
          author {
            login
            ... on User {
              avatarUrl
            }
          }
          labels(first: 10) {
            edges {
              node {
                name
              }
            }
          }
          hasApprovedReview: reviews(first: 5, states: [APPROVED]) {  # Check for at least one approved review
            edges {
              node {
                author {
                  login
                }
                state
              }
            }
          }
          mergedBy {
            login
          }
        }
      }
    }
  }
}

{
  "query": "label:hacktoberfest-accepted is:pr is:merged created:>2023-10-01 review:approved -label:spam -label:invalid -label:duplicate -label:automerge",
  "firstIssues": 100
}